#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 10 09:00:51 2021

@author: julian
"""

name = input("What is your name ")
age = input("How old are you? ")
print("Your name is ", name, "and you are ", age, "years old")

