#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 10 09:00:51 2021

@author: julian
"""

name = input("What is your name ")
age = input("How old are you? ")
hundred = (100 - int(age)) + 2021
print("Your name is ", name, "and you are ", age, "years old.  You will be 100 in ", hundred)

